config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit, :index, :update]
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  root to: "homes#top"
 get 'home/about' =>  "homes#about" ,as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
         
  has_one_attached :profile_image, dependent: :destroy
  
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
 before_action :authenticate_user!, except: [:top, :about]
 before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  add_flash_types :log_in, :log_out, :new
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
   before_action :is_matching_login_user, only: [:edit, :update]
   
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:create] = "You have created book successfully."
      redirect_to @book
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = current_user
  end
  

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:update] = "You have updated book successfully."
      redirect_to @book
    else
      render :edit
    end
  end
  
  def destroy
    @book = Book.find(params[:id]) 
    @book.destroy
    redirect_to books_path
  end
  
    private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def is_matching_login_user
    @book = Book.find(params[:id])
    if(@book.user != current_user)
      redirect_to books_path
    end
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :is_matching_login_user, only: [:edit, :update]
    
  def show
    @user = User.find(params[:id])
    # @user_show =current_user
    @books = @user.books
    @book = Book.new
  end
  
  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id]) 
  end
    
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:pfupdate] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render:edit
    end
  end
 
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  
  def is_matching_login_user
    user_id = params[:id].to_i
    login_user_id = current_user.id
    if(user_id != login_user_id)
      redirect_to user_path(login_user_id)
    end
  end
  
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <table class="table">
        <tbody>
          <tr>
            <th><%= image_tag user.get_profile_image(100,100) %></th>
          </tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
         <i class="fas fa-user-cog"></i>
        <% end %>
      
      <%= form_with model: book do |f| %>
      <h2 class="mt-3">New book</h2>
        <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control book_title" %>
        <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book_body" %>
          <%= f.submit 'Create Book', class: "btn btn-success" %>
      <% end %>
        </div>
</div>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>



<p id="notice"></p>
<div class="contaier">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= form_with model:@book, url: book_path(@book.id), method: :patch do |f| %>
      <h1>Editing Book</h1>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class:"form-control book_title" %>
        </div>
         <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book_body"%>
        </div>
         <div class="form-group">
           <%= f.submit 'Update Book', class: "btn btn-success" %>
         </div>
      <% end %>
      <%= link_to book_path(@book.id) do %>Show<% end %>
      |
      <%= link_to books_path do %>Back<% end %>
    </div>
  </div>
</div>

<!--<#%= form_with model: @book do |f| %>-->

<!--  <h4>title</h4>-->
<!--  <%#= f.text_field :title %>-->
  
<!--  <h4>opinion</h4>-->
<!--  <%#= f.text_area :body %>-->
  
<!--  <%#= f.submit '保存' %>-->
  
<!--<%# end %>-->

app/views/books/index.html.erb
<main>
  
   <% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'show', user: @user, book: @book %>
 
 
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <th>
              <%=link_to user_path(book.id) do %>
              　<%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
            </th>
            <th>
              <%=link_to book_path(book.id) do %>
               <%= book.title %>
              <% end %>
            </th>
            <th><%= book.body %></th>
            <th></th>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
</main>

app/views/books/new.html.erb
<!--<h1>New Book</h1>-->

<!--<%# if @book.errors.any? %>-->
<!--  <%#= @book.errors.count %>prohibited this obj from being saved::-->
<!--  <ul>-->
<!--    <%# @book.errors.full_messages.each do |message| %>-->
<!--      <li><%#= message %></li>-->
<!--    <%# end %>-->
<!--  </ul>-->
<!--<%# end %>-->

<!--  <%#= form_with model: @book do |f| %>-->
<!--    <h4>title</h4>-->
<!--      <%#= f.text_field :title %>-->
<!--    <h4>opinion</h4>-->
<!--      <%#= f.text_area :body %>-->
<!--    <%#= f.submit 'Create Book' %>-->
<!--  <%# end %>-->
  

app/views/books/show.html.erb
<div>
  <%= flash[:create] %>
</div>

<div>
  <%= flash[:update] %>
</div>

<%= render 'show' , user: @book.user, book: @book_new %>

<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table">
    <tbody>
      <tr>
        <td>
          <%=link_to (@book.user) do %>
            <%= image_tag @book.user.get_profile_image(100,100) %>
            <br>
            <%= @book.user.name %>
          <% end %>
        </td>
        <td>
          <%= link_to book_path(@book.id) do %>
            <%= @book.title %>
          <% end %>
          </td>
        <td><%= @book.body %></td>
        <td>
            <% if @book.user == current_user %>
              <%= link_to "Edit", edit_book_path, class:"btn btn-sm btn-success" %>
            <% end %>
        </td>
        <td>
            <% if @book.user == current_user %>
              <%= link_to "Destroy", book_path(@book), method: :delete, class:"btn btn-sm btn-danger", "data-confirm" => "本当に削除しますか？"%>
            <% end %>
        </td>
      </tr>
    </tbody>
  </table>
  
  <!--<p>title：<%#= @book.title %></p>-->
  <!--<p>Opinion：<%#= @book.body %></p>-->
  <!--<p><%#= image_tag @book.user.get_profile_image(100,100) %></p>-->
  <!--<p>ユーザーネーム：<%#= @book.user.name %></p>-->
  <!--<%#= link_to "Edit", edit_book_path(@book.id) %>-->
  <!--<%#= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>-->
</div>

app/views/homes/about.html.erb
 <p id="notice">
      <div class="container">
        <div class="row">
          <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>welcome to 
            <i class="fas fa-book"></i>
            <strong>Bookers</strong>
            !</h1>
          </div>
        </div>
      </div>
 </p>

app/views/homes/top.html.erb
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
  <head>
    
  </head>
  
  <body>
    
    <main>
      <p id="notice"></p>
      <div class="container">
        <div class="row">
          <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>"welcome to "
            <!--<svg class="svg-inline-fa fa-book fa-w-14" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="book" role="img" xmlns="" viewBox="0 0 448 512" data-fa-i2svg>-->
              <i class="fas fa-book"></i>
            <strong>Bookers</strong>
            " !!"</h1>
            <p>In <i class"fas fa-book"></i><strong>Bookers</strong>,</p>
            <p>you can exchange your opinions, inpressions, andemotions</p>
            <p>about various books!</p>
            <div class="btn-wrapper col-10 mx-auto">
              <div class="row">
                <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3" %>
                <!--<a class="btn btn-info btn-sm btn-block mb-3 sign in" href="/users/sign_in">Log in</a>-->
              </div>
              <div class="row">
                <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block" %>
                <!--<a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>-->
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
      
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tag %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%#= render 'shared/flash_message' %>
     <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to root_path, class: "navbar-brand" do %>
          <span>Bookers</span>
          <% end %>
          <!--<a class="navbar-brand" href="/">-->
          <!--  <span>Bookers</span>-->
          <!--</a>-->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
               <li> 
                <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
                  <i class="fas fa-home"></i>
                  Home
                <% end %>
              </li>
               <li>
                 <%= link_to users_path, class:'nav-link text-light' do %>
                  <i class="fas fa-users"></i>
                   Users 
                <% end %>
              </li>
               <li>
                <%= link_to books_path, class:'nav-link text-light' do %>
                  <i class="fas fa-book-open"></i>
                   Books 
                <% end %>
              </li>
               <li>
                 <%= link_to destroy_user_session_path,  method: :delete, class:'nav-link text-light' do %>
                <!--<a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">-->
                <i class="fas fa-sign-out-alt"></i>
                   Log out 
                <% end %>
              </li>
              <% else %>
              <li> 
                <%= link_to root_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-home"></i>
                  Home
                <% end %>
              </li>
              <li>
                <%= link_to about_path, class:'nav-link text-light' do %>
                  <i class="fas fa-link"></i>
                   About 
                <% end %>
              </li>
               <li>
                <%= link_to new_user_registration_path, class:'nav-link text-light' do %>
                  <i class="fas fa-user-plus"></i>
                   Sign up 
                <% end %>
              </li>
               <li>
                <%= link_to new_user_session_path, class:'nav-link text-light' do %>
                  <i class="fas fa-sign-in-alt"></i>
                   Log in 
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
  </header>
  
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "{key}") %>
      <% end %>
  
   
    <%= yield %>
  </body>
  
  <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div> 
      </div>
    </footer>
    
</html>

app/views/users/_show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <table class="table">
        <tbody>
          <tr>
            <th><%= image_tag user.get_profile_image(100,100) %></th>
          </tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
         <i class="fas fa-user-cog"></i>
        <% end %>
      <%= form_with model: @book do |f| %>
      <h2 class="mt-3">New Book</h2>
        <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control book_title" %>
        <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book_body" %>
          <%= f.submit 'Create Book', class: "btn btn-success" %>
      <% end %>
        </div>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @user do |f| %>
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h2>User info</h2>
    <label for="user_name">Name</label>
      <%= f.text_field :name, class: "form-control name" %>
    <label for="user_image">Image</label>
      <%= f.file_field :profile_image, class: "form-control-file user_image" %>
    <label for="user_introduction">Introduction</label>
      <%= f.text_area :introduction, class: "form-control introduction" %>
    <%= f.submit "Update User", class: "btn btn-secondary" %>
</div>
<% end %>

app/views/users/index.html.erb
<%= render 'books/show', user: @user, book: @book %>

<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(100,100) %></td>
        <td><%= user.name %></td>
        <td>
          <%= link_to user_path(user.id) do %>
          Show
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<%= flash[:pfupdate] %>

<%= render 'books/show', user: @user, book: @book %>


<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <th>
          <%= link_to user_path do %>
            <%= image_tag book.user.get_profile_image(100,100) %>
          <% end %>
            </th>
        <th>
          <%= link_to book_path(book.id) do %>
            <%= book.title %>
          <% end %>
        </th>
        <th><%= book.body %></th>
        <th></th>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>




<!--<div>-->
<!--  <h3><%#= @user.name %></h3>-->
<!--  <%#= image_tag @user.get_profile_image(100,100) %>-->
  
<!--</div>-->

<!--<%# @books.each do |book| %>-->
<!--<div>-->
<!--  <%#= link_to book_path(book.id) do %>-->
<!--  <p><%#= image_tag book.user.get_profile_image(100,100) %></p>-->
<!--  <p><%#= book.title %></p>-->
<!--  <p><%#= book.body %></p>-->
<!--  <p><%#= book.user.name %></p>-->
<!--</div>-->
<!--<%# end %>-->